<?php
/**
 * ==========================================
 * AUTOGENERATED FROM POSTGRESQL DATA
 * DO NOT EDIT DIRECTLY!!!
 * TO MODIFY, EDIT scripts/generate_enums.php
 * ==========================================
 * 
 * AddressType Enum 
 *
 * @author      A Computer
 * @copyright   (c) 2015 G2G Market, Inc
 ********************************** 80 Columns *********************************
 */

namespace Pikd\Enums;

class AddressType {

	const BILLING = 'Billing';
	const SHIPPING = 'Shipping';

}