<?php
/**
 * ==========================================
 * AUTOGENERATED FROM POSTGRESQL DATA
 * DO NOT EDIT DIRECTLY!!!
 * TO MODIFY, EDIT THIS FILE:
 * app/Console/Commands/GenerateEnums.php
 * ==========================================
 *
 * ExpirationClass Enum
 *
 * @author      A Computer
 * @copyright   (c) 2015 G2G Market, Inc
 ********************************** 80 Columns *********************************
 */

namespace Pikd\Enums;

class ExpirationClass {

    const A = 'A';
    const B = 'B';
    const C = 'C';
}
