<?php
/**
 * ==========================================
 * AUTOGENERATED FROM POSTGRESQL DATA
 * DO NOT EDIT DIRECTLY!!!
 * TO MODIFY, EDIT THIS FILE:
 * app/Console/Commands/GenerateEnums.php
 * ==========================================
 * 
 * OrderStatus Enum 
 *
 * @author      A Computer
 * @copyright   (c) 2015 G2G Market, Inc
 ********************************** 80 Columns *********************************
 */

namespace Pikd\Enums;

class OrderStatus {

	const BASKET = 'Basket';
	const SHOPPING_LIST = 'Shopping List';
	const PENDING_PICKUP = 'Pending Pickup';
	const COMPLETE = 'Complete';
	const CANCELLED = 'Cancelled';
	const PROCESSING = 'Processing';

}