<?php
/**
 * ==========================================
 * AUTOGENERATED FROM POSTGRESQL DATA
 * DO NOT EDIT DIRECTLY!!!
 * TO MODIFY, EDIT scripts/generate_enums.php
 * ==========================================
 * 
 * ProductStatus Enum 
 *
 * @author      A Computer
 * @copyright   (c) 2015 G2G Market, Inc
 ********************************** 80 Columns *********************************
 */

namespace Pikd\Enums;

class ProductStatus {

	const ACTIVE = 'Active';
	const BEING_ADDED = 'Being Added';
	const TEMPORARILY_UNAVAILABLE = 'Temporarily Unavailable';
	const DISCONTINUED = 'Discontinued';
	const DUMMY = 'Dummy';

}