<?php
/**
 * ==========================================
 * AUTOGENERATED FROM POSTGRESQL DATA
 * DO NOT EDIT DIRECTLY!!!
 * TO MODIFY, EDIT THIS FILE:
 * app/Console/Commands/GenerateEnums.php
 * ==========================================
 *
 * ReferralStatus Enum
 *
 * @author      A Computer
 * @copyright   (c) 2015 G2G Market, Inc
 ********************************** 80 Columns *********************************
 */

namespace Pikd\Enums;

class ReferralStatus {

    const REFERRED = 'Referred';
    const CREATED_ACCOUNT = 'Created Account';
    const PLACED_AN_ORDER = 'Placed An Order';
    const CREDITED = 'Credited';
}
